/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author admin
 */
public class MyProfile extends javax.swing.JPanel {

    /**
     * Creates new form MyProfile
     */
    public MyProfile() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelcolon10 = new javax.swing.JLabel();
        labelcolon13 = new javax.swing.JLabel();
        labelcolon15 = new javax.swing.JLabel();
        lblEmpname14 = new javax.swing.JLabel();
        pnl1 = new javax.swing.JPanel();
        lblMyProfile = new javax.swing.JLabel();
        pnl2 = new javax.swing.JPanel();
        txtEmpPosition = new javax.swing.JLabel();
        txtEmpName = new javax.swing.JLabel();
        pnl3 = new javax.swing.JPanel();
        lblLastname = new javax.swing.JLabel();
        lblBday = new javax.swing.JLabel();
        labelcolon3 = new javax.swing.JLabel();
        labelcolon4 = new javax.swing.JLabel();
        txtLastname = new javax.swing.JLabel();
        lblEmpname5 = new javax.swing.JLabel();
        lblFirstname = new javax.swing.JLabel();
        labelcolon5 = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JLabel();
        lblPhoneNo = new javax.swing.JLabel();
        labelcolon6 = new javax.swing.JLabel();
        txtPhoneNo = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        labelcolon7 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JLabel();
        lblPersonalInfo = new javax.swing.JLabel();
        pnl4 = new javax.swing.JPanel();
        lblEmployeeDetails = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblPosition = new javax.swing.JLabel();
        lblImmediateSupervisor = new javax.swing.JLabel();
        labelcolon8 = new javax.swing.JLabel();
        labelcolon9 = new javax.swing.JLabel();
        labelcolon11 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();
        txtImmediateSupervisor = new javax.swing.JLabel();
        txtPosition = new javax.swing.JLabel();
        pnl5 = new javax.swing.JPanel();
        lblGovernmentIdentificationNumber = new javax.swing.JLabel();
        lblSSSNo = new javax.swing.JLabel();
        lblPhilhealthNo = new javax.swing.JLabel();
        lblPagIbigNo = new javax.swing.JLabel();
        lblTINNo = new javax.swing.JLabel();
        labelcolon12 = new javax.swing.JLabel();
        labelcolon14 = new javax.swing.JLabel();
        labelcolon16 = new javax.swing.JLabel();
        labelcolon17 = new javax.swing.JLabel();
        txtSSSNo = new javax.swing.JLabel();
        txtPhilhealthNo = new javax.swing.JLabel();
        txtPagIbigNo = new javax.swing.JLabel();
        txtTINNo = new javax.swing.JLabel();

        labelcolon10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon10.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon10.setText(":");

        labelcolon13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon13.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon13.setText(":");

        labelcolon15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon15.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon15.setText(":");

        lblEmpname14.setBackground(new java.awt.Color(204, 204, 204));
        lblEmpname14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmpname14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        pnl1.setBackground(new java.awt.Color(255, 255, 255));

        lblMyProfile.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblMyProfile.setForeground(new java.awt.Color(51, 51, 51));
        lblMyProfile.setText("MY PROFILE");

        pnl2.setBackground(new java.awt.Color(204, 204, 204));

        txtEmpPosition.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpPosition.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmpPosition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtEmpName.setBackground(new java.awt.Color(204, 204, 204));
        txtEmpName.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtEmpName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout pnl2Layout = new javax.swing.GroupLayout(pnl2);
        pnl2.setLayout(pnl2Layout);
        pnl2Layout.setHorizontalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtEmpName, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
                    .addComponent(txtEmpPosition, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl2Layout.setVerticalGroup(
            pnl2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl2Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtEmpPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        pnl3.setBackground(new java.awt.Color(204, 204, 204));

        lblLastname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblLastname.setForeground(new java.awt.Color(51, 51, 51));
        lblLastname.setText("Last Name");

        lblBday.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblBday.setForeground(new java.awt.Color(51, 51, 51));
        lblBday.setText("Birthday");

        labelcolon3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon3.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon3.setText(":");

        labelcolon4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon4.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon4.setText(":");

        txtLastname.setBackground(new java.awt.Color(204, 204, 204));
        txtLastname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtLastname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblEmpname5.setBackground(new java.awt.Color(204, 204, 204));
        lblEmpname5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmpname5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblFirstname.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblFirstname.setForeground(new java.awt.Color(51, 51, 51));
        lblFirstname.setText("First Name");

        labelcolon5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon5.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon5.setText(":");

        txtFirstname.setBackground(new java.awt.Color(204, 204, 204));
        txtFirstname.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtFirstname.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblPhoneNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPhoneNo.setForeground(new java.awt.Color(51, 51, 51));
        lblPhoneNo.setText("Phone Number");

        labelcolon6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon6.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon6.setText(":");

        txtPhoneNo.setBackground(new java.awt.Color(204, 204, 204));
        txtPhoneNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPhoneNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblAddress.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(51, 51, 51));
        lblAddress.setText("Address");

        labelcolon7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon7.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon7.setText(":");

        txtAddress.setBackground(new java.awt.Color(204, 204, 204));
        txtAddress.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtAddress.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        lblPersonalInfo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblPersonalInfo.setForeground(new java.awt.Color(51, 51, 51));
        lblPersonalInfo.setText("Personal Information");

        javax.swing.GroupLayout pnl3Layout = new javax.swing.GroupLayout(pnl3);
        pnl3.setLayout(pnl3Layout);
        pnl3Layout.setHorizontalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPhoneNo)
                            .addComponent(lblBday)
                            .addComponent(lblLastname))
                        .addGap(15, 15, 15)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(labelcolon3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                                .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(labelcolon6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addComponent(labelcolon4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblEmpname5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(lblPersonalInfo))
                .addGap(46, 46, 46)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblAddress)
                    .addComponent(lblFirstname))
                .addGap(15, 15, 15)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(labelcolon7)
                        .addGap(20, 20, 20)
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addComponent(labelcolon5)
                        .addGap(20, 20, 20)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl3Layout.setVerticalGroup(
            pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl3Layout.createSequentialGroup()
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblFirstname)
                                    .addComponent(labelcolon7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAddress)
                                    .addComponent(labelcolon5)))
                            .addGroup(pnl3Layout.createSequentialGroup()
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(pnl3Layout.createSequentialGroup()
                                        .addComponent(lblPersonalInfo)
                                        .addGap(20, 20, 20)
                                        .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLastname)
                                            .addComponent(labelcolon3))))
                                .addGap(15, 15, 15)
                                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblBday)
                                        .addComponent(labelcolon4))
                                    .addComponent(lblEmpname5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(pnl3Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(15, 15, 15)
                .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPhoneNo)
                        .addComponent(labelcolon6))
                    .addComponent(txtPhoneNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pnl4.setBackground(new java.awt.Color(204, 204, 204));

        lblEmployeeDetails.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEmployeeDetails.setForeground(new java.awt.Color(51, 51, 51));
        lblEmployeeDetails.setText("Employee Details");

        lblStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblStatus.setForeground(new java.awt.Color(51, 51, 51));
        lblStatus.setText("Status");

        lblPosition.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPosition.setForeground(new java.awt.Color(51, 51, 51));
        lblPosition.setText("Position");

        lblImmediateSupervisor.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblImmediateSupervisor.setForeground(new java.awt.Color(51, 51, 51));
        lblImmediateSupervisor.setText("Immediate Supervisor");

        labelcolon8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon8.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon8.setText(":");

        labelcolon9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon9.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon9.setText(":");

        labelcolon11.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon11.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon11.setText(":");

        txtStatus.setBackground(new java.awt.Color(204, 204, 204));
        txtStatus.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtStatus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtImmediateSupervisor.setBackground(new java.awt.Color(204, 204, 204));
        txtImmediateSupervisor.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtImmediateSupervisor.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtPosition.setBackground(new java.awt.Color(204, 204, 204));
        txtPosition.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPosition.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout pnl4Layout = new javax.swing.GroupLayout(pnl4);
        pnl4.setLayout(pnl4Layout);
        pnl4Layout.setHorizontalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl4Layout.createSequentialGroup()
                        .addComponent(lblImmediateSupervisor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelcolon11))
                    .addComponent(lblEmployeeDetails)
                    .addGroup(pnl4Layout.createSequentialGroup()
                        .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblStatus)
                            .addComponent(lblPosition))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelcolon9, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(labelcolon8, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(18, 18, 18)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtImmediateSupervisor, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        pnl4Layout.setVerticalGroup(
            pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl4Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(lblEmployeeDetails)
                .addGap(20, 20, 20)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblStatus)
                        .addComponent(labelcolon8))
                    .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblPosition)
                        .addComponent(labelcolon9)))
                .addGap(15, 15, 15)
                .addGroup(pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblImmediateSupervisor)
                        .addComponent(labelcolon11))
                    .addComponent(txtImmediateSupervisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl5.setBackground(new java.awt.Color(204, 204, 204));

        lblGovernmentIdentificationNumber.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGovernmentIdentificationNumber.setForeground(new java.awt.Color(51, 51, 51));
        lblGovernmentIdentificationNumber.setText("Government Identification Number");

        lblSSSNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSSSNo.setForeground(new java.awt.Color(51, 51, 51));
        lblSSSNo.setText("SSS #");

        lblPhilhealthNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPhilhealthNo.setForeground(new java.awt.Color(51, 51, 51));
        lblPhilhealthNo.setText("Philhealth #");

        lblPagIbigNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPagIbigNo.setForeground(new java.awt.Color(51, 51, 51));
        lblPagIbigNo.setText("Pag-ibig #");

        lblTINNo.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblTINNo.setForeground(new java.awt.Color(51, 51, 51));
        lblTINNo.setText("TIN #");

        labelcolon12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon12.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon12.setText(":");

        labelcolon14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon14.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon14.setText(":");

        labelcolon16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon16.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon16.setText(":");

        labelcolon17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon17.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon17.setText(":");

        txtSSSNo.setBackground(new java.awt.Color(204, 204, 204));
        txtSSSNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtSSSNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtPhilhealthNo.setBackground(new java.awt.Color(204, 204, 204));
        txtPhilhealthNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPhilhealthNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtPagIbigNo.setBackground(new java.awt.Color(204, 204, 204));
        txtPagIbigNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtPagIbigNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        txtTINNo.setBackground(new java.awt.Color(204, 204, 204));
        txtTINNo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        txtTINNo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        javax.swing.GroupLayout pnl5Layout = new javax.swing.GroupLayout(pnl5);
        pnl5.setLayout(pnl5Layout);
        pnl5Layout.setHorizontalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGovernmentIdentificationNumber)
                    .addGroup(pnl5Layout.createSequentialGroup()
                        .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(pnl5Layout.createSequentialGroup()
                                .addComponent(lblTINNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelcolon17))
                            .addGroup(pnl5Layout.createSequentialGroup()
                                .addComponent(lblPagIbigNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelcolon16))
                            .addGroup(pnl5Layout.createSequentialGroup()
                                .addComponent(lblPhilhealthNo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelcolon14))
                            .addGroup(pnl5Layout.createSequentialGroup()
                                .addComponent(lblSSSNo)
                                .addGap(48, 48, 48)
                                .addComponent(labelcolon12)))
                        .addGap(18, 18, 18)
                        .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSSSNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPhilhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPagIbigNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTINNo, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        pnl5Layout.setVerticalGroup(
            pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl5Layout.createSequentialGroup()
                        .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pnl5Layout.createSequentialGroup()
                                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(pnl5Layout.createSequentialGroup()
                                        .addComponent(lblGovernmentIdentificationNumber)
                                        .addGap(20, 20, 20)
                                        .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblSSSNo)
                                            .addComponent(labelcolon12)))
                                    .addComponent(txtSSSNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblPhilhealthNo)
                                    .addComponent(labelcolon14)))
                            .addComponent(txtPhilhealthNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblPagIbigNo)
                            .addComponent(labelcolon16)))
                    .addComponent(txtPagIbigNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pnl5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTINNo)
                        .addComponent(labelcolon17))
                    .addComponent(txtTINNo, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl1Layout = new javax.swing.GroupLayout(pnl1);
        pnl1.setLayout(pnl1Layout);
        pnl1Layout.setHorizontalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl1Layout.createSequentialGroup()
                        .addComponent(pnl4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pnl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblMyProfile)
                    .addComponent(pnl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        pnl1Layout.setVerticalGroup(
            pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblMyProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnl2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(pnl3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(pnl1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelcolon10;
    private javax.swing.JLabel labelcolon11;
    private javax.swing.JLabel labelcolon12;
    private javax.swing.JLabel labelcolon13;
    private javax.swing.JLabel labelcolon14;
    private javax.swing.JLabel labelcolon15;
    private javax.swing.JLabel labelcolon16;
    private javax.swing.JLabel labelcolon17;
    private javax.swing.JLabel labelcolon3;
    private javax.swing.JLabel labelcolon4;
    private javax.swing.JLabel labelcolon5;
    private javax.swing.JLabel labelcolon6;
    private javax.swing.JLabel labelcolon7;
    private javax.swing.JLabel labelcolon8;
    private javax.swing.JLabel labelcolon9;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblBday;
    private javax.swing.JLabel lblEmployeeDetails;
    private javax.swing.JLabel lblEmpname14;
    private javax.swing.JLabel lblEmpname5;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblGovernmentIdentificationNumber;
    private javax.swing.JLabel lblImmediateSupervisor;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblMyProfile;
    private javax.swing.JLabel lblPagIbigNo;
    private javax.swing.JLabel lblPersonalInfo;
    private javax.swing.JLabel lblPhilhealthNo;
    private javax.swing.JLabel lblPhoneNo;
    private javax.swing.JLabel lblPosition;
    private javax.swing.JLabel lblSSSNo;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTINNo;
    private javax.swing.JPanel pnl1;
    private javax.swing.JPanel pnl2;
    private javax.swing.JPanel pnl3;
    private javax.swing.JPanel pnl4;
    private javax.swing.JPanel pnl5;
    private javax.swing.JLabel txtAddress;
    private javax.swing.JLabel txtEmpName;
    private javax.swing.JLabel txtEmpPosition;
    private javax.swing.JLabel txtFirstname;
    private javax.swing.JLabel txtImmediateSupervisor;
    private javax.swing.JLabel txtLastname;
    private javax.swing.JLabel txtPagIbigNo;
    private javax.swing.JLabel txtPhilhealthNo;
    private javax.swing.JLabel txtPhoneNo;
    private javax.swing.JLabel txtPosition;
    private javax.swing.JLabel txtSSSNo;
    private javax.swing.JLabel txtStatus;
    private javax.swing.JLabel txtTINNo;
    // End of variables declaration//GEN-END:variables
}
