/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author admin
 */
public class PayrollProcessing extends javax.swing.JPanel {

    /**
     * Creates new form PayrollProcessing
     */
    public PayrollProcessing() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane8 = new javax.swing.JTabbedPane();
        hoursComputationTab = new javax.swing.JPanel();
        labelPayCoverage = new javax.swing.JLabel();
        jcbDateRange = new javax.swing.JComboBox<>();
        btnCompute = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPaneloverScrollPane = new javax.swing.JPanel();
        lblEarnings = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblMonthlyRate = new javax.swing.JLabel();
        lblDailyRate = new javax.swing.JLabel();
        lblDaysWorked = new javax.swing.JLabel();
        lblOvertime = new javax.swing.JLabel();
        lblEarningsGrossIncome = new javax.swing.JLabel();
        lblBenefits = new javax.swing.JLabel();
        txtMonthlyRateOutput = new javax.swing.JTextField();
        txtDailyRateOutput = new javax.swing.JTextField();
        txtDaysWorkedOutput = new javax.swing.JTextField();
        txtEarningsGrossIncomeOutput = new javax.swing.JTextField();
        txtOvertimeOutput = new javax.swing.JTextField();
        lblRiceSubsidy = new javax.swing.JLabel();
        lblPhoneAllowance = new javax.swing.JLabel();
        lblClothingAllowance = new javax.swing.JLabel();
        lblGrossIncome1 = new javax.swing.JLabel();
        txtClothingAllowanceOutput = new javax.swing.JTextField();
        txtRiceSubsidyOutput = new javax.swing.JTextField();
        txtPhoneAllowanceOutput = new javax.swing.JTextField();
        txtWithholdingTaxOutput = new javax.swing.JTextField();
        lblDeductions = new javax.swing.JLabel();
        lblSSS = new javax.swing.JLabel();
        lblPhilhealth = new javax.swing.JLabel();
        lblPagIbig = new javax.swing.JLabel();
        lblWithholdingTax = new javax.swing.JLabel();
        lblTtlDeductions = new javax.swing.JLabel();
        txtTotalOutput1 = new javax.swing.JTextField();
        txtSSSOutput = new javax.swing.JTextField();
        txtPhHealthOutput = new javax.swing.JTextField();
        txtPagIbigOutput = new javax.swing.JTextField();
        txtTotalDeductionsOutput = new javax.swing.JTextField();
        lblSummary = new javax.swing.JLabel();
        lblGrossIncome = new javax.swing.JLabel();
        lblSummaryBenefits = new javax.swing.JLabel();
        lblSummaryDeductions = new javax.swing.JLabel();
        lblTakeHomePay = new javax.swing.JLabel();
        txtSummaryBenefitsOutput = new javax.swing.JTextField();
        txtGrossIncomeOutput = new javax.swing.JTextField();
        txtSummaryDeductionsOutput = new javax.swing.JTextField();
        txtTakeHomePayOutput = new javax.swing.JTextField();
        lblEmployeePayslip = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        btnUpdate = new javax.swing.JButton();

        jPanel1.setMaximumSize(null);

        jPanel2.setMaximumSize(null);
        jPanel2.setLayout(new javax.swing.BoxLayout(jPanel2, javax.swing.BoxLayout.LINE_AXIS));

        jTabbedPane8.setMaximumSize(null);

        hoursComputationTab.setMaximumSize(null);

        labelPayCoverage.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelPayCoverage.setText("Pay Coverage");

        jcbDateRange.setFont(new java.awt.Font("Arial", 2, 12)); // NOI18N
        jcbDateRange.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Pay Period..." }));

        btnCompute.setBackground(new java.awt.Color(0, 51, 0));
        btnCompute.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnCompute.setForeground(new java.awt.Color(255, 255, 255));
        btnCompute.setText("Compute");
        btnCompute.setToolTipText("");
        btnCompute.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComputeActionPerformed(evt);
            }
        });

        jScrollPane1.setMaximumSize(new java.awt.Dimension(460, 750));
        jScrollPane1.setMinimumSize(new java.awt.Dimension(460, 750));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(460, 750));

        jPaneloverScrollPane.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jPaneloverScrollPane.setMaximumSize(new java.awt.Dimension(570, 750));
        jPaneloverScrollPane.setMinimumSize(new java.awt.Dimension(570, 750));
        jPaneloverScrollPane.setRequestFocusEnabled(false);

        lblEarnings.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEarnings.setText("EARNINGS");

        lblMonthlyRate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblMonthlyRate.setText("Monthly Rate");

        lblDailyRate.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDailyRate.setText("Daily Rate");

        lblDaysWorked.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblDaysWorked.setText("Days Worked");

        lblOvertime.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblOvertime.setText("Overtime");

        lblEarningsGrossIncome.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblEarningsGrossIncome.setText("GROSS INCOME");

        lblBenefits.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblBenefits.setText("BENEFITS");

        txtMonthlyRateOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDailyRateOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtDaysWorkedOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtEarningsGrossIncomeOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtOvertimeOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblRiceSubsidy.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblRiceSubsidy.setText("Rice Subsidy");

        lblPhoneAllowance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPhoneAllowance.setText("Phone Allowance");

        lblClothingAllowance.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblClothingAllowance.setText("Clothing Allowance");

        lblGrossIncome1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblGrossIncome1.setText("TOTAL");

        txtClothingAllowanceOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtRiceSubsidyOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtPhoneAllowanceOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtWithholdingTaxOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblDeductions.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblDeductions.setText("DEDUCTIONS");

        lblSSS.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSSS.setText("Social Security System");

        lblPhilhealth.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPhilhealth.setText("Philhealth");

        lblPagIbig.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblPagIbig.setText("Pag-Ibig");

        lblWithholdingTax.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblWithholdingTax.setText("Withholding Tax");

        lblTtlDeductions.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTtlDeductions.setText("TOTAL DEDUCTIONS");

        txtTotalOutput1.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtSSSOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtPhHealthOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtPagIbigOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTotalDeductionsOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblSummary.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblSummary.setText("SUMMARY");

        lblGrossIncome.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblGrossIncome.setText("Gross Income");

        lblSummaryBenefits.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSummaryBenefits.setText("Benefits");

        lblSummaryDeductions.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        lblSummaryDeductions.setText("Deductions");

        lblTakeHomePay.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lblTakeHomePay.setText("TAKE HOME PAY");

        txtSummaryBenefitsOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtGrossIncomeOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtSummaryDeductionsOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        txtTakeHomePayOutput.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        lblEmployeePayslip.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblEmployeePayslip.setText("EMPLOYEE PAYSLIP");

        btnUpdate.setBackground(new java.awt.Color(0, 51, 0));
        btnUpdate.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPaneloverScrollPaneLayout = new javax.swing.GroupLayout(jPaneloverScrollPane);
        jPaneloverScrollPane.setLayout(jPaneloverScrollPaneLayout);
        jPaneloverScrollPaneLayout.setHorizontalGroup(
            jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                        .addGap(230, 230, 230)
                        .addComponent(lblEmployeePayslip))
                    .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                                    .addComponent(lblSummary)
                                    .addGap(10, 10, 10)
                                    .addComponent(jSeparator4))
                                .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                                    .addComponent(lblDeductions)
                                    .addGap(10, 10, 10)
                                    .addComponent(jSeparator3))
                                .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                                    .addComponent(lblBenefits)
                                    .addGap(10, 10, 10)
                                    .addComponent(jSeparator2))
                                .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                                    .addComponent(lblEarnings)
                                    .addGap(10, 10, 10)
                                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btnUpdate)
                                    .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                                        .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(lblOvertime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDaysWorked, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblDailyRate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblMonthlyRate, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(lblEarningsGrossIncome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(lblPhoneAllowance, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(lblClothingAllowance, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(lblGrossIncome1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(lblPhilhealth)
                                            .addComponent(lblSSS, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(lblPagIbig)
                                            .addComponent(lblWithholdingTax)
                                            .addComponent(lblTtlDeductions)
                                            .addComponent(lblSummaryBenefits)
                                            .addComponent(lblGrossIncome, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                                            .addComponent(lblSummaryDeductions)
                                            .addComponent(lblTakeHomePay)
                                            .addComponent(lblRiceSubsidy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(50, 50, 50)
                                        .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtMonthlyRateOutput, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                                            .addComponent(txtDailyRateOutput)
                                            .addComponent(txtDaysWorkedOutput)
                                            .addComponent(txtOvertimeOutput)
                                            .addComponent(txtEarningsGrossIncomeOutput)
                                            .addComponent(txtRiceSubsidyOutput)
                                            .addComponent(txtPhoneAllowanceOutput)
                                            .addComponent(txtClothingAllowanceOutput)
                                            .addComponent(txtTotalOutput1)
                                            .addComponent(txtSSSOutput)
                                            .addComponent(txtPhHealthOutput)
                                            .addComponent(txtPagIbigOutput)
                                            .addComponent(txtWithholdingTaxOutput)
                                            .addComponent(txtTotalDeductionsOutput)
                                            .addComponent(txtGrossIncomeOutput)
                                            .addComponent(txtSummaryBenefitsOutput)
                                            .addComponent(txtSummaryDeductionsOutput)
                                            .addComponent(txtTakeHomePayOutput))))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPaneloverScrollPaneLayout.setVerticalGroup(
            jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPaneloverScrollPaneLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblEmployeePayslip)
                .addGap(20, 20, 20)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblEarnings)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMonthlyRateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMonthlyRate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDailyRate)
                    .addComponent(txtDailyRateOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDaysWorked)
                    .addComponent(txtDaysWorkedOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblOvertime)
                    .addComponent(txtOvertimeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEarningsGrossIncome)
                    .addComponent(txtEarningsGrossIncomeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblBenefits)
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRiceSubsidy)
                    .addComponent(txtRiceSubsidyOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhoneAllowance)
                    .addComponent(txtPhoneAllowanceOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtClothingAllowanceOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblClothingAllowance))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrossIncome1)
                    .addComponent(txtTotalOutput1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblDeductions)
                    .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSSS)
                    .addComponent(txtSSSOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPhilhealth)
                    .addComponent(txtPhHealthOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPagIbig)
                    .addComponent(txtPagIbigOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblWithholdingTax)
                    .addComponent(txtWithholdingTaxOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTtlDeductions)
                    .addComponent(txtTotalDeductionsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSummary)
                    .addGroup(jPaneloverScrollPaneLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGrossIncome)
                    .addComponent(txtGrossIncomeOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSummaryBenefits)
                    .addComponent(txtSummaryBenefitsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSummaryDeductions)
                    .addComponent(txtSummaryDeductionsOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPaneloverScrollPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTakeHomePay)
                    .addComponent(txtTakeHomePayOutput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(btnUpdate)
                .addGap(59, 59, 59))
        );

        jScrollPane1.setViewportView(jPaneloverScrollPane);

        javax.swing.GroupLayout hoursComputationTabLayout = new javax.swing.GroupLayout(hoursComputationTab);
        hoursComputationTab.setLayout(hoursComputationTabLayout);
        hoursComputationTabLayout.setHorizontalGroup(
            hoursComputationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoursComputationTabLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(hoursComputationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                    .addGroup(hoursComputationTabLayout.createSequentialGroup()
                        .addComponent(labelPayCoverage, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jcbDateRange, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCompute, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        hoursComputationTabLayout.setVerticalGroup(
            hoursComputationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(hoursComputationTabLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(hoursComputationTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPayCoverage)
                    .addComponent(jcbDateRange, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCompute))
                .addGap(5, 5, 5)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, Short.MAX_VALUE))
        );

        jTabbedPane8.addTab("Salary Computation", hoursComputationTab);

        jPanel2.add(jTabbedPane8);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 610, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnComputeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComputeActionPerformed
        String sel = (String) jcbDateRange.getSelectedItem();
        if (employeeTimeRecord == null) {
            JOptionPane.showMessageDialog(this, "Employee data not loaded.");
            return;
        }
        if (sel == null || !sel.contains(" to ")) {
            JOptionPane.showMessageDialog(this, "Please select a valid pay period.");
            return;
        }

        try {
            String[] parts    = sel.split(" to ");
            LocalDate start   = LocalDate.parse(parts[0], ISO_DATE);
            // (end date parsed but not used directly)
            LocalDate end     = LocalDate.parse(parts[1], ISO_DATE);

            double monthlyRate = Double.parseDouble(salaryField.getText());
            double dailyRate   = monthlyRate / start.lengthOfMonth();

            int totalHours     = employeeTimeRecord.getTotalHoursWorked(parts[0], parts[1]);
            double daysWorked  = totalHours / 8.0;
            double overtime    = totalHours % 8;
            double hourlyRate  = employeeTimeRecord.getHourlyRate();
            double grossIncome = totalHours * hourlyRate;

            double rice        = employeeTimeRecord.getRiceSubsidy();
            double phone       = employeeTimeRecord.getPhoneAllowance();
            double cloth       = employeeTimeRecord.getClothingAllowance();
            double benefits    = rice + phone + cloth;

            double sssDed      = grossIncome * 0.045;
            double phDed       = grossIncome * 0.035;
            double piDed       = grossIncome * 0.02;
            double taxDed      = grossIncome * 0.10;
            double totalDed    = sssDed + phDed + piDed + taxDed;

            double takeHome    = grossIncome + benefits - totalDed;

            // Populate UI outputs (two‐decimal format)
            txtMonthlyRateOutput.setText(String.format("%.2f", monthlyRate));
            txtDailyRateOutput.setText(  String.format("%.2f", dailyRate));
            txtDaysWorkedOutput.setText( String.format("%.2f", daysWorked));
            txtOvertimeOutput.setText(   String.format("%.2f", overtime));
            txtEarningsGrossIncomeOutput.setText(String.format("%.2f", grossIncome));

            txtRiceSubsidyOutput.setText(      String.format("%.2f", rice));
            txtPhoneAllowanceOutput.setText(   String.format("%.2f", phone));
            txtClothingAllowanceOutput.setText(String.format("%.2f", cloth));
            txtTotalOutput1.setText(           String.format("%.2f", benefits));

            txtSSSOutput.setText(            String.format("%.2f", sssDed));
            txtPhHealthOutput.setText(       String.format("%.2f", phDed));
            txtPagIbigOutput.setText(        String.format("%.2f", piDed));
            txtWithholdingTaxOutput.setText( String.format("%.2f", taxDed));
            txtTotalDeductionsOutput.setText(String.format("%.2f", totalDed));

            txtGrossIncomeOutput.setText(      String.format("%.2f", grossIncome));
            txtSummaryBenefitsOutput.setText(  String.format("%.2f", benefits));
            txtSummaryDeductionsOutput.setText(String.format("%.2f", totalDed));
            txtTakeHomePayOutput.setText(      String.format("%.2f", takeHome));

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(this,
                "Invalid numeric value in salary.\n" + nfe.getMessage());
        }
    }//GEN-LAST:event_btnComputeActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnUpdateActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCompute;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JPanel hoursComputationTab;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPaneloverScrollPane;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane8;
    private javax.swing.JComboBox<String> jcbDateRange;
    private javax.swing.JLabel labelPayCoverage;
    private javax.swing.JLabel lblBenefits;
    private javax.swing.JLabel lblClothingAllowance;
    private javax.swing.JLabel lblDailyRate;
    private javax.swing.JLabel lblDaysWorked;
    private javax.swing.JLabel lblDeductions;
    private javax.swing.JLabel lblEarnings;
    private javax.swing.JLabel lblEarningsGrossIncome;
    private javax.swing.JLabel lblEmployeePayslip;
    private javax.swing.JLabel lblGrossIncome;
    private javax.swing.JLabel lblGrossIncome1;
    private javax.swing.JLabel lblMonthlyRate;
    private javax.swing.JLabel lblOvertime;
    private javax.swing.JLabel lblPagIbig;
    private javax.swing.JLabel lblPhilhealth;
    private javax.swing.JLabel lblPhoneAllowance;
    private javax.swing.JLabel lblRiceSubsidy;
    private javax.swing.JLabel lblSSS;
    private javax.swing.JLabel lblSummary;
    private javax.swing.JLabel lblSummaryBenefits;
    private javax.swing.JLabel lblSummaryDeductions;
    private javax.swing.JLabel lblTakeHomePay;
    private javax.swing.JLabel lblTtlDeductions;
    private javax.swing.JLabel lblWithholdingTax;
    private javax.swing.JTextField txtClothingAllowanceOutput;
    private javax.swing.JTextField txtDailyRateOutput;
    private javax.swing.JTextField txtDaysWorkedOutput;
    private javax.swing.JTextField txtEarningsGrossIncomeOutput;
    private javax.swing.JTextField txtGrossIncomeOutput;
    private javax.swing.JTextField txtMonthlyRateOutput;
    private javax.swing.JTextField txtOvertimeOutput;
    private javax.swing.JTextField txtPagIbigOutput;
    private javax.swing.JTextField txtPhHealthOutput;
    private javax.swing.JTextField txtPhoneAllowanceOutput;
    private javax.swing.JTextField txtRiceSubsidyOutput;
    private javax.swing.JTextField txtSSSOutput;
    private javax.swing.JTextField txtSummaryBenefitsOutput;
    private javax.swing.JTextField txtSummaryDeductionsOutput;
    private javax.swing.JTextField txtTakeHomePayOutput;
    private javax.swing.JTextField txtTotalDeductionsOutput;
    private javax.swing.JTextField txtTotalOutput1;
    private javax.swing.JTextField txtWithholdingTaxOutput;
    // End of variables declaration//GEN-END:variables
}
