/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

/**
 *
 * @author admin
 */
public class ResetPassword extends javax.swing.JPanel {

    /**
     * Creates new form ResetPassword
     */
    public ResetPassword() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblResetPassword = new javax.swing.JLabel();
        textFieldEmpID = new javax.swing.JTextField();
        buttonSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        labelEmpName = new javax.swing.JLabel();
        labelcolon1 = new javax.swing.JLabel();
        txtFieldEmpName = new javax.swing.JTextField();
        labelDep = new javax.swing.JLabel();
        labelcolon2 = new javax.swing.JLabel();
        txtFieldEmpName1 = new javax.swing.JTextField();
        labelStatus = new javax.swing.JLabel();
        labelcolon3 = new javax.swing.JLabel();
        txtFieldEmpName2 = new javax.swing.JTextField();
        labelNewPassword = new javax.swing.JLabel();
        labelcolon4 = new javax.swing.JLabel();
        txtFieldEmpName3 = new javax.swing.JTextField();
        buttonSearch2 = new javax.swing.JButton();
        buttonSearch3 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Employee ID:");

        lblResetPassword.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lblResetPassword.setForeground(new java.awt.Color(51, 51, 51));
        lblResetPassword.setText("RESET PASSWORD");

        textFieldEmpID.setBackground(new java.awt.Color(204, 204, 204));
        textFieldEmpID.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        textFieldEmpID.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        buttonSearch.setBackground(new java.awt.Color(0, 51, 0));
        buttonSearch.setFont(new java.awt.Font("Arial", 1, 10)); // NOI18N
        buttonSearch.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch.setText("Search");
        buttonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearchActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        labelEmpName.setBackground(new java.awt.Color(51, 51, 51));
        labelEmpName.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelEmpName.setForeground(new java.awt.Color(51, 51, 51));
        labelEmpName.setText("Employee Name");

        labelcolon1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon1.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon1.setText(":");

        txtFieldEmpName.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtFieldEmpName.setCaretColor(new java.awt.Color(153, 153, 153));
        txtFieldEmpName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmpNameActionPerformed(evt);
            }
        });

        labelDep.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelDep.setForeground(new java.awt.Color(51, 51, 51));
        labelDep.setText("Department");

        labelcolon2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon2.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon2.setText(":");

        txtFieldEmpName1.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName1.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtFieldEmpName1.setCaretColor(new java.awt.Color(153, 153, 153));
        txtFieldEmpName1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmpName1ActionPerformed(evt);
            }
        });

        labelStatus.setBackground(new java.awt.Color(51, 51, 51));
        labelStatus.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelStatus.setForeground(new java.awt.Color(51, 51, 51));
        labelStatus.setText("Status");

        labelcolon3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon3.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon3.setText(":");

        txtFieldEmpName2.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName2.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtFieldEmpName2.setCaretColor(new java.awt.Color(153, 153, 153));
        txtFieldEmpName2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmpName2ActionPerformed(evt);
            }
        });

        labelNewPassword.setBackground(new java.awt.Color(51, 51, 51));
        labelNewPassword.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        labelNewPassword.setForeground(new java.awt.Color(51, 51, 51));
        labelNewPassword.setText("New Password");

        labelcolon4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        labelcolon4.setForeground(new java.awt.Color(51, 51, 51));
        labelcolon4.setText(":");

        txtFieldEmpName3.setBackground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName3.setForeground(new java.awt.Color(153, 153, 153));
        txtFieldEmpName3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        txtFieldEmpName3.setCaretColor(new java.awt.Color(153, 153, 153));
        txtFieldEmpName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFieldEmpName3ActionPerformed(evt);
            }
        });

        buttonSearch2.setBackground(new java.awt.Color(0, 51, 0));
        buttonSearch2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonSearch2.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch2.setText("Reset Password");
        buttonSearch2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearch2ActionPerformed(evt);
            }
        });

        buttonSearch3.setBackground(new java.awt.Color(153, 0, 0));
        buttonSearch3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        buttonSearch3.setForeground(new java.awt.Color(255, 255, 255));
        buttonSearch3.setText("Cancel");
        buttonSearch3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSearch3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(labelStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelDep, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(labelEmpName))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelcolon1)
                                    .addComponent(labelcolon2)
                                    .addComponent(labelcolon3)))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(labelNewPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(labelcolon4)))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFieldEmpName3)
                            .addComponent(txtFieldEmpName2)
                            .addComponent(txtFieldEmpName1)
                            .addComponent(txtFieldEmpName)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonSearch2)
                        .addGap(36, 36, 36)
                        .addComponent(buttonSearch3, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(45, 45, 45))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmpName)
                    .addComponent(labelcolon1)
                    .addComponent(txtFieldEmpName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelDep)
                    .addComponent(labelcolon2)
                    .addComponent(txtFieldEmpName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelStatus)
                    .addComponent(labelcolon3)
                    .addComponent(txtFieldEmpName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNewPassword)
                    .addComponent(labelcolon4)
                    .addComponent(txtFieldEmpName3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(122, 122, 122)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonSearch2)
                    .addComponent(buttonSearch3))
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(20, 20, 20)
                        .addComponent(textFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblResetPassword)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lblResetPassword)
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldEmpID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearchActionPerformed
        getEmployeeInfo(textFieldEmpID.getText());
    }//GEN-LAST:event_buttonSearchActionPerformed

    private void txtFieldEmpNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmpNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmpNameActionPerformed

    private void txtFieldEmpName1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmpName1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmpName1ActionPerformed

    private void txtFieldEmpName2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmpName2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmpName2ActionPerformed

    private void txtFieldEmpName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFieldEmpName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFieldEmpName3ActionPerformed

    private void buttonSearch2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearch2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearch2ActionPerformed

    private void buttonSearch3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSearch3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_buttonSearch3ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonSearch;
    private javax.swing.JButton buttonSearch2;
    private javax.swing.JButton buttonSearch3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel labelDep;
    private javax.swing.JLabel labelEmpName;
    private javax.swing.JLabel labelNewPassword;
    private javax.swing.JLabel labelStatus;
    private javax.swing.JLabel labelcolon1;
    private javax.swing.JLabel labelcolon2;
    private javax.swing.JLabel labelcolon3;
    private javax.swing.JLabel labelcolon4;
    private javax.swing.JLabel lblResetPassword;
    private javax.swing.JTextField textFieldEmpID;
    private javax.swing.JTextField txtFieldEmpName;
    private javax.swing.JTextField txtFieldEmpName1;
    private javax.swing.JTextField txtFieldEmpName2;
    private javax.swing.JTextField txtFieldEmpName3;
    // End of variables declaration//GEN-END:variables
}
